export const CONNECT_MODAL_SHOW = 'CONNECT_MODAL_SHOW';
export const CONNECT_MODAL_HIDE = 'CONNECT_MODAL_HIDE';

export const CONNECT_METAMASK_ERROR = 'CONNECT_METAMASK_ERROR';
export const CONNECT_METAMASK_IN_PROGRESS = 'CONNECT_METAMASK_IN_PROGRESS';
export const CONNECT_METAMASK_SUCCESS = 'CONNECT_METAMASK_SUCCESS';

export const CONNECT_LEDGER_ERROR = 'CONNECT_LEDGER_ERROR';
export const CONNECT_LEDGER_IN_PROGRESS = 'CONNECT_LEDGER_IN_PROGRESS';
export const CONNECT_LEDGER_SUCCESS = 'CONNECT_LEDGER_SUCCESS';
