export const CONTRACT_ERC20_ADDRESS = process.env.REACT_APP_CONTRACT_ERC20_ADDRESS;
export const CONTRACT_ERC20_DECIMALS = +process.env.REACT_APP_CONTRACT_ERC20_DECIMALS;
export const CONTRACT_SWAP_ADDRESS = process.env.REACT_APP_CONTRACT_SWAP_ADDRESS;
