export const TX_ALLOWANCE_IN_PROGRESS = 'TX_ALLOWANCE_IN_PROGRESS';
export const TX_ALLOWANCE_ERROR = 'TX_ALLOWANCE_ERROR';
export const TX_ALLOWANCE_SUCCESS = 'TX_ALLOWANCE_SUCCESS';

export const TX_BURN_AMOUNT_SET = 'TX_BURN_AMOUNT_SET';
export const TX_BURN_TO_ADDRESS_SET = 'TX_BURN_TO_ADDRESS_SET';

export const TX_BURN_IN_PROGRESS = 'TX_BURN_IN_PROGRESS';
export const TX_BURN_ERROR = 'TX_BURN_ERROR';
export const TX_BURN_SUCCESS = 'TX_BURN_SUCCESS';
